import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-pink-50 text-rose-950">
        <div className="min-h-screen bg-[radial-gradient(circle_at_top_left,#ffe4ef,transparent_35%),radial-gradient(circle_at_top_right,#f3e8ff,transparent_30%),linear-gradient(#fff7fb,#fff)]">
          <nav className="sticky top-0 z-50 border-b border-pink-100 bg-white/70 backdrop-blur-md">
            <div className="mx-auto flex max-w-6xl items-center justify-between p-4">
              <a href="/" className="text-2xl font-black text-pink-500 drop-shadow-sm">
                MacroBudget ♡
              </a>

              <div className="flex gap-2 text-sm font-semibold">
                <a className="rounded-full px-4 py-2 text-rose-700 hover:bg-pink-100" href="/">
                  Dashboard
                </a>
                <a className="rounded-full px-4 py-2 text-rose-700 hover:bg-pink-100" href="/ingredients">
                  Ingredients
                </a>
                <a className="rounded-full px-4 py-2 text-rose-700 hover:bg-pink-100" href="/recipes">
                  Recipes
                </a>
                <a className="rounded-full px-4 py-2 text-rose-700 hover:bg-pink-100" href="/meal-plan">
                  Meal Plan
                </a>
              </div>
            </div>
          </nav>

          {children}
        </div>
      </body>
    </html>
  );
}
